sudo: false

language: python

python:
   - "2.7"

before_install:
    - cat .travis.yml
    - pip install --upgrade pip
    - pip --version

install:
    - pip install certifi==2018.1.18
    - pip install chardet==3.0.4
    - pip install click==6.7
    - pip install Flask==0.12.2
    - pip install Flask-REST-JSONAPI==0.17.0
    - pip install Flask-Restless==0.17.0
    - pip install Flask-SQLAlchemy==2.3.2
    - pip install fmt==0.3.1
    - pip install funcsigs==1.0.2
    - pip install idna==2.6
    - pip install itsdangerous==0.24
    - pip install Jinja2==2.10
    - pip install MarkupSafe==1.0
    - pip install marshmallow==2.13.1
    - pip install marshmallow-jsonapi==0.16.0
    - pip install mimerender==0.6.0
    - pip install mock==2.0.0
    - pip install mysqlclient==1.3.12
    - pip install pbr==3.1.1
    - pip install python-dateutil==2.7.0
    - pip install python-mimeparse==1.6.0
    - pip install requests==2.18.4
    - pip install six==1.11.0
    - pip install SQLAlchemy==1.2.5
    - pip install urllib3==1.22
    - pip install Werkzeug==0.14.1
    - pip list

# branches: 
#     - master
#     - alexdai-dev
before_script:
    - date
    - uname -a
    - printenv | sort
    - git       --version
    - make      --version
    - ls -al

script:
    - cd tests
    - chmod +x ./dbtests.py
    - chmod +x ./tests.py
    - python ./dbtests.py
    - python ./tests.py